name: Run Banking Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chrome, firefox]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup Chrome
        if: matrix.browser == 'chrome'
        uses: browser-actions/setup-chrome@latest

      - name: Setup Firefox
        if: matrix.browser == 'firefox'
        uses: browser-actions/setup-firefox@latest

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r Guru99BankAutomation/requirements.txt
          pip install allure-pytest selenium webdriver-manager

      - name: Run tests with ${{ matrix.browser }}
        env:
          CI: true
          BROWSER: ${{ matrix.browser }}
        run: pytest Guru99BankAutomation/tests/ --browser=${{ matrix.browser }} --alluredir=reports/${{ matrix.browser }} -v

      - name: Upload Allure Results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: allure-results-${{ matrix.browser }}
          path: reports/${{ matrix.browser }}